name: (Ingress) Publish Images

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          dotnet publish \
            /t:PublishContainer \
            --configuration Release \
            -p:ContainerRegistry=ghcr.io
            -p:ContainerRuntimeIdentifiers="linux-x64;linux-arm64"
        working-directory: ./src/YarpContrib.Kubernetes.Ingress.Controller
        env:
          ContainerImageTags: "${{ github.sha }};latest"

      - run: |
          dotnet publish \
            /t:PublishContainer \
            --configuration Release \
            -p:ContainerRegistry=ghcr.io
            -p:ContainerRuntimeIdentifiers="linux-x64;linux-arm64"
        working-directory: ./src/YarpContrib.Kubernetes.Ingress.Monitor
        env:
          ContainerImageTags: "${{ github.sha }};latest"